### PR TITLE
Misc. cleanup.

### PR DESCRIPTION
**Pull request by arb**
Updated .travis
Removed Makefile
Lint cleanup
lab command update

### CODE REVIEW

**Comment by arb** [comment]
This should probably be re-published when this gets merged. npm hasn't been updated with the documentation yet so it looks like this module has no documentation.

**Comment by hueniverse** [comment]
@arb you want to take over this module?

**Comment by arb** [comment]
Sure. I've got bandwidth.

**Comment by hueniverse** [comment]
Great. Take over.

**Pull request merged**
